/**
 * FlowFOR Creative — Smart Launch Command Center
 * Built for #JuaraVibeCoding by Google using Claude Code and Gemini Pro
 * © 2026 Rangga Danu Arta. All rights reserved.
 * Unauthorized copying or redistribution is prohibited.
 */

import JSZip from "jszip";
import { saveAs } from "file-saver";

export interface ExportData {
  productName: string;
  contentType: string;
  landingPage: string;
  caption: string;
  broadcast: string;
  todoList: string[];
  storyboard: { shot: string; visual: string; audio: string }[];
  vibeScore: { vibeScore: number; label: string; reasons: string[]; quickFix?: string };
  contentCalendar?: {
    day: number;
    date: string;
    platform: string;
    type: string;
    topic: string;
    caption_hint: string;
  }[];
  shootScript?: {
    format: string;
    duration: string;
    scenes: {
      scene: string;
      action: string;
      dialogue: string;
      camera: string;
    }[];
    tips: string[];
  };
  nicheRecommendation?: string;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 50);
}

function stripHtml(text: string): string {
  return text.replace(/<[^>]*>/g, "").replace(/&[a-z]+;/gi, (m) => {
    const map: Record<string, string> = {
      "&amp;": "&", "&lt;": "<", "&gt;": ">", "&quot;": '"', "&#39;": "'", "&nbsp;": " ",
    };
    return map[m] ?? m;
  });
}

function formatDate(): string {
  return new Date().toLocaleDateString("id-ID", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

export async function exportCampaignToZip(data: ExportData): Promise<void> {
  const zip = new JSZip();
  const baseName = slugify(data.productName || "Campaign");
  const dateStr = formatDate();

  // ─── README.txt ───
  zip.file(
    "README.txt",
    `FlowFOR Creative — Launch Kit Export
===================================
Product: ${data.productName}
Content Type: ${data.contentType}
Generated: ${dateStr}
Powered by FlowFOR Creative | #JuaraVibeCoding | Built with Claude Code & Gemini Pro
https://flow-for-creative.vercel.app

ATTENTION:
All content in this package is generated by AI (Google Gemini 2.5 Flash, Claude Code & Gemini Pro)
and should be reviewed before publishing.
`
  );

  // ─── 01-Sales-Page.txt ───
  zip.file(
    "01-Sales-Page.txt",
    `SALES PAGE — ${data.productName}
${"=".repeat(60)}
${data.contentType}

${stripHtml(data.landingPage)}
`
  );

  // ─── 02-Social-Caption.txt ───
  zip.file(
    "02-Social-Caption.txt",
    `SOCIAL CAPTION — ${data.productName}
${"=".repeat(60)}
Platform: Instagram / TikTok

${data.caption}
`
  );

  // ─── 03-Broadcast-Message.txt ───
  zip.file(
    "03-Broadcast-Message.txt",
    `BROADCAST MESSAGE — ${data.productName}
${"=".repeat(60)}
Platform: WhatsApp / Telegram

${data.broadcast}
`
  );

  // ─── 04-Todo-List.txt ───
  zip.file(
    "04-Todo-List.txt",
    `LAUNCH TO-DO LIST — ${data.productName}
${"=".repeat(60)}

${data.todoList.map((item, i) => `${i + 1}. ${item}`).join("\n")}
`
  );

  // ─── 05-Visual-Storyboard.txt ───
  zip.file(
    "05-Visual-Storyboard.txt",
    `VISUAL STORYBOARD — ${data.productName}
${"=".repeat(60)}

${data.storyboard
  .map(
    (s, i) =>
      `SHOT ${i + 1}\n${s.shot}\nVisual: ${s.visual}\nAudio: ${s.audio}`
  )
  .join("\n\n")}
`
  );

  // ─── 06-Vibe-Score.txt ───
  zip.file(
    "06-Vibe-Score.txt",
    `VIBE SCORE — ${data.productName}
${"=".repeat(60)}

SCORE: ${data.vibeScore.vibeScore}/100
LABEL: ${data.vibeScore.label}

ANALYSIS:
${data.vibeScore.reasons.map((r, i) => `${i + 1}. ${r}`).join("\n")}
`
  );

  // ─── 07-Content-Calendar.txt ───
  if (data.contentCalendar && data.contentCalendar.length > 0) {
    zip.file(
      "07-Content-Calendar.txt",
      `CONTENT CALENDAR — ${data.productName}
${"=".repeat(60)}

${data.contentCalendar
  .map(
    (c) =>
      `${c.date} | ${c.platform} | ${c.type}\nTopic: ${c.topic}\nCaption Hint: ${c.caption_hint}`
  )
  .join("\n\n")}
`
    );
  }

  // ─── 08-Shoot-Script.txt ───
  if (data.shootScript) {
    const ss = data.shootScript;
    zip.file(
      "08-Shoot-Script.txt",
      `SHOOT SCRIPT — ${data.productName}
${"=".repeat(60)}
Format: ${ss.format}
Duration: ${ss.duration}

${ss.scenes
  .map(
    (s, i) =>
      `SCENE ${i + 1}: ${s.scene}\nAction: ${s.action}\nDialogue: ${s.dialogue}\nCamera: ${s.camera}`
  )
  .join("\n\n")}

PRODUCTION TIPS:
${ss.tips.map((t, i) => `${i + 1}. ${t}`).join("\n")}
`
    );
  }

  // ─── 09-Niche-Recommendation.txt (optional) ───
  if (data.nicheRecommendation) {
    zip.file(
      "09-Niche-Recommendation.txt",
      `NICHE RECOMMENDATION — ${data.productName}
${"=".repeat(60)}

${data.nicheRecommendation}
`
    );
  }

  // Generate ZIP
  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  const fileName = `FlowFOR-${baseName}-${new Date().toISOString().split("T")[0]}.zip`;
  saveAs(blob, fileName);
}